version: '3.9'

services:
  core:
    image: test
    container_name: resume-back
    ports:
      - "8080:8080"
    logging:
      driver: 'json-file'
      options:
        max-size: '100m'
        max-file: '3'